# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimerWindow(object):
    def setupUi(self, TimerWindow):
        TimerWindow.setObjectName("TimerWindow")
        TimerWindow.resize(475, 290)
        TimerWindow.setMinimumSize(QtCore.QSize(336, 222))
        TimerWindow.setMaximumSize(QtCore.QSize(475, 290))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(11)
        TimerWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("statics/clock_select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TimerWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(TimerWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber_hours = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_hours.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_hours.setLineWidth(1)
        self.lcdNumber_hours.setMidLineWidth(0)
        self.lcdNumber_hours.setDigitCount(2)
        self.lcdNumber_hours.setProperty("intValue", -1)
        self.lcdNumber_hours.setObjectName("lcdNumber_hours")
        self.horizontalLayout.addWidget(self.lcdNumber_hours)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setMaximumSize(QtCore.QSize(20, 20))
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.lcdNumber_minutes = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_minutes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_minutes.setLineWidth(0)
        self.lcdNumber_minutes.setDigitCount(2)
        self.lcdNumber_minutes.setProperty("intValue", -1)
        self.lcdNumber_minutes.setObjectName("lcdNumber_minutes")
        self.horizontalLayout.addWidget(self.lcdNumber_minutes)
        self.line2 = QtWidgets.QFrame(self.centralWidget)
        self.line2.setMinimumSize(QtCore.QSize(20, 20))
        self.line2.setMaximumSize(QtCore.QSize(20, 20))
        self.line2.setLineWidth(4)
        self.line2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")
        self.horizontalLayout.addWidget(self.line2)
        self.lcdNumber_seconds = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber_seconds.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_seconds.setLineWidth(0)
        self.lcdNumber_seconds.setDigitCount(2)
        self.lcdNumber_seconds.setProperty("intValue", -1)
        self.lcdNumber_seconds.setObjectName("lcdNumber_seconds")
        self.horizontalLayout.addWidget(self.lcdNumber_seconds)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 2, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_earning = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_earning.setFont(font)
        self.groupBox_earning.setObjectName("groupBox_earning")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_earning)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lcdNumber_earning = QtWidgets.QLCDNumber(self.groupBox_earning)
        self.lcdNumber_earning.setDigitCount(10)
        self.lcdNumber_earning.setObjectName("lcdNumber_earning")
        self.gridLayout_3.addWidget(self.lcdNumber_earning, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_earning, 0, 0, 1, 1)
        self.groupBox_all_month = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_all_month.setFont(font)
        self.groupBox_all_month.setObjectName("groupBox_all_month")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_all_month)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumber_all_month = QtWidgets.QLCDNumber(self.groupBox_all_month)
        self.lcdNumber_all_month.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_all_month.setSmallDecimalPoint(False)
        self.lcdNumber_all_month.setDigitCount(10)
        self.lcdNumber_all_month.setProperty("value", 1.2)
        self.lcdNumber_all_month.setObjectName("lcdNumber_all_month")
        self.gridLayout_2.addWidget(self.lcdNumber_all_month, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_all_month, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        TimerWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(TimerWindow)
        self.mainToolBar.setMinimumSize(QtCore.QSize(0, 199))
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        TimerWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TimerWindow)
        self.statusBar.setObjectName("statusBar")
        TimerWindow.setStatusBar(self.statusBar)
        self.action_playpause = QtWidgets.QAction(TimerWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("statics/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_playpause.setIcon(icon1)
        self.action_playpause.setObjectName("action_playpause")
        self.action_stop = QtWidgets.QAction(TimerWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("statics/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_stop.setIcon(icon2)
        self.action_stop.setObjectName("action_stop")
        self.mainToolBar.addAction(self.action_playpause)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.action_stop)
        self.mainToolBar.addSeparator()

        self.retranslateUi(TimerWindow)
        QtCore.QMetaObject.connectSlotsByName(TimerWindow)

    def retranslateUi(self, TimerWindow):
        _translate = QtCore.QCoreApplication.translate
        TimerWindow.setWindowTitle(_translate("TimerWindow", "Timer"))
        self.groupBox_earning.setTitle(_translate("TimerWindow", "Earning ($)"))
        self.groupBox_all_month.setTitle(_translate("TimerWindow", "All-Month ($)"))
        self.action_playpause.setText(_translate("TimerWindow", "PlayPause"))
        self.action_playpause.setShortcut(_translate("TimerWindow", "F5, Space, Ctrl+Z"))
        self.action_stop.setText(_translate("TimerWindow", "Stop"))
        self.action_stop.setShortcut(_translate("TimerWindow", "Ctrl+C, Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimerWindow = QtWidgets.QMainWindow()
    ui = Ui_TimerWindow()
    ui.setupUi(TimerWindow)
    TimerWindow.show()
    sys.exit(app.exec_())

